### ISSUE TITLE
Some Documentation

### ISSUE THREAD

**Issue by dwalter0** [nccgroup/PS2#2]
Recommend adding some examples to the readme so that users don't need to parse the heap of parameters and parameter groups to figure out how this works.

For the top 1000 tcp scan do
.\ps2.ps1 -ips 192.168.43.130 -tcp

for udp
.\ps2.ps1 -ips 192.168.43.130 -udp

to just ping
.\ps2.ps1 -ips 192.168.43.130 -ping

**Comment by JamesConlan96** [comment]
Examples have been added to the help info
